import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    {name: 'global', title: 'Global', default: true},
    {name: 'home', title: 'Home'},
    {name: 'works', title: 'Works'},
    {name: 'journal', title: 'Journal'},
    {name: 'album', title: 'My Album'},
    {name: 'contact', title: 'Contact'},
  ],
  fields: [
    defineField({
      name: 'siteTitle',
      title: 'Site Title',
      type: 'string',
      group: 'global',
    }),
    defineField({
      name: 'email',
      title: 'Email',
      type: 'string',
      group: ['global', 'contact'],
    }),
    defineField({
      name: 'instagramPrimary',
      title: 'Instagram Primary',
      type: 'string',
      group: ['global', 'contact'],
    }),
    defineField({
      name: 'instagramSecondary',
      title: 'Instagram Secondary',
      type: 'string',
      group: ['global', 'contact'],
    }),

    defineField({
      name: 'hero',
      title: 'Hero',
      type: 'object',
      group: 'home',
      fields: [
        defineField({name: 'roleLine', title: 'Role Line', type: 'string'}),
        defineField({name: 'headline', title: 'Headline', type: 'string'}),
        defineField({name: 'intro', title: 'Intro', type: 'text', rows: 4}),
        defineField({name: 'sequenceLabel', title: 'Sequence Label', type: 'string'}),
        defineField({name: 'topSubLabel', title: 'Top Sub Label', type: 'string'}),
        defineField({name: 'railLeftTitle', title: 'Rail Left Title', type: 'string'}),
        defineField({name: 'railLeftSubtitle', title: 'Rail Left Subtitle', type: 'string'}),
        defineField({name: 'railRightTitle', title: 'Rail Right Title', type: 'string'}),
        defineField({name: 'ctaPrimaryLabel', title: 'CTA Primary Label', type: 'string'}),
        defineField({name: 'ctaSecondaryLabel', title: 'CTA Secondary Label', type: 'string'}),
        defineField({name: 'ctaTertiaryLabel', title: 'CTA Tertiary Label', type: 'string'}),
      ],
    }),

    defineField({
      name: 'about',
      title: 'About',
      type: 'object',
      group: 'home',
      fields: [
        defineField({name: 'sectionLabel', title: 'Section Label', type: 'string'}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'body', title: 'Body', type: 'text', rows: 6}),
        defineField({name: 'secondaryBody', title: 'Secondary Body', type: 'text', rows: 6}),
        defineField({name: 'focusLabel', title: 'Focus Label', type: 'string'}),
        defineField({
          name: 'focusTags',
          title: 'Focus Tags',
          type: 'array',
          of: [{type: 'string'}],
        }),
      ],
    }),

    defineField({
      name: 'works',
      title: 'Home Works Section',
      type: 'object',
      group: 'home',
      fields: [
        defineField({name: 'sectionLabel', title: 'Section Label', type: 'string'}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text', rows: 4}),
        defineField({name: 'metaLabel', title: 'Meta Label', type: 'string'}),
        defineField({name: 'metaBody', title: 'Meta Body', type: 'text', rows: 3}),
        defineField({name: 'archiveButtonLabel', title: 'Archive Button Label', type: 'string'}),
      ],
    }),

    defineField({
      name: 'journal',
      title: 'Home Journal Section',
      type: 'object',
      group: 'home',
      fields: [
        defineField({name: 'sectionLabel', title: 'Section Label', type: 'string'}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text', rows: 4}),
        defineField({name: 'ctaLabel', title: 'CTA Label', type: 'string'}),
        defineField({name: 'helperText', title: 'Helper Text', type: 'string'}),
      ],
    }),

    defineField({
      name: 'albumGateway',
      title: 'Home Album Section',
      type: 'object',
      group: 'home',
      fields: [
        defineField({name: 'sectionLabel', title: 'Section Label', type: 'string'}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text', rows: 4}),
        defineField({name: 'buttonLabel', title: 'Button Label', type: 'string'}),
        defineField({name: 'noteLabel', title: 'Note Label', type: 'string'}),
      ],
    }),

    defineField({
      name: 'worksPage',
      title: 'Works Archive Page',
      type: 'object',
      group: 'works',
      fields: [
        defineField({name: 'pageLabel', title: 'Page Label', type: 'string'}),
        defineField({name: 'pageIntro', title: 'Page Intro', type: 'text', rows: 3}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text', rows: 4}),
        defineField({name: 'statsBoardsLabel', title: 'Stats Boards Label', type: 'string'}),
        defineField({name: 'statsPublishedLabel', title: 'Stats Published Label', type: 'string'}),
        defineField({name: 'statsNavigationLabel', title: 'Stats Navigation Label', type: 'string'}),
        defineField({name: 'statsNavigationValue', title: 'Stats Navigation Value', type: 'string'}),
        defineField({name: 'boardEyebrow', title: 'Board Eyebrow', type: 'string'}),
        defineField({name: 'boardDescription', title: 'Board Description', type: 'text', rows: 3}),
        defineField({name: 'boardSheetTypeLabel', title: 'Board Sheet Type Label', type: 'string'}),
        defineField({name: 'boardSheetTypeValue', title: 'Board Sheet Type Value', type: 'string'}),
        defineField({name: 'boardLoadedFramesLabel', title: 'Board Loaded Frames Label', type: 'string'}),
        defineField({name: 'boardStatusLabel', title: 'Board Status Label', type: 'string'}),
        defineField({name: 'boardStatusValue', title: 'Board Status Value', type: 'string'}),
        defineField({name: 'boardNextFillLabel', title: 'Board Next Fill Label', type: 'string'}),
        defineField({name: 'boardStorySheetLabel', title: 'Board Story Sheet Label', type: 'string'}),
        defineField({name: 'boardClickHint', title: 'Board Click Hint', type: 'string'}),
        defineField({name: 'boardEmptyFrameLabel', title: 'Empty Frame Label', type: 'string'}),
        defineField({name: 'boardEmptyFrameDescription', title: 'Empty Frame Description', type: 'string'}),
        defineField({name: 'boardStoryFrameLabel', title: 'Story Frame Label', type: 'string'}),
        defineField({name: 'boardOpenCaseStudyLabel', title: 'Open Case Study Label', type: 'string'}),
      ],
    }),

    defineField({
      name: 'projectPage',
      title: 'Project Detail Page',
      type: 'object',
      group: 'works',
      fields: [
        defineField({name: 'pageLabel', title: 'Page Label', type: 'string'}),
        defineField({name: 'overviewLabel', title: 'Overview Label', type: 'string'}),
        defineField({name: 'overviewTitle', title: 'Overview Title', type: 'string'}),
        defineField({name: 'contributionLabel', title: 'Contribution Label', type: 'string'}),
        defineField({name: 'contributionTitle', title: 'Contribution Title', type: 'string'}),
        defineField({name: 'approachLabel', title: 'Approach Label', type: 'string'}),
        defineField({name: 'approachTitle', title: 'Approach Title', type: 'string'}),
        defineField({name: 'quoteLabel', title: 'Quote Label', type: 'string'}),
        defineField({name: 'highlightsLabel', title: 'Highlights Label', type: 'string'}),
        defineField({name: 'frameStudyLabel', title: 'Frame Study Label', type: 'string'}),
        defineField({name: 'frameStudyTitle', title: 'Frame Study Title', type: 'string'}),
        defineField({name: 'processNotesLabel', title: 'Process Notes Label', type: 'string'}),
        defineField({name: 'processNotesTitle', title: 'Process Notes Title', type: 'string'}),
        defineField({name: 'creditsLabel', title: 'Credits Label', type: 'string'}),
        defineField({name: 'metaLabel', title: 'Meta Label', type: 'string'}),
        defineField({name: 'boardPageLabel', title: 'Board Page Label', type: 'string'}),
        defineField({name: 'boardOrderLabel', title: 'Board Order Label', type: 'string'}),
        defineField({name: 'boardLabelText', title: 'Board Label Label', type: 'string'}),
        defineField({name: 'boardCaptionLabel', title: 'Board Caption Label', type: 'string'}),
        defineField({name: 'publishedAtLabel', title: 'Published At Label', type: 'string'}),
        defineField({name: 'continueReadingLabel', title: 'Continue Reading Label', type: 'string'}),
        defineField({name: 'previousChapterLabel', title: 'Previous Chapter Label', type: 'string'}),
        defineField({name: 'nextChapterLabel', title: 'Next Chapter Label', type: 'string'}),
        defineField({name: 'sequenceStartLabel', title: 'Sequence Start Label', type: 'string'}),
        defineField({name: 'sequenceEndLabel', title: 'Sequence End Label', type: 'string'}),
      ],
    }),

    defineField({
      name: 'journalPage',
      title: 'Journal Page',
      type: 'object',
      group: 'journal',
      fields: [
        defineField({name: 'pageLabel', title: 'Page Label', type: 'string'}),
        defineField({name: 'pageIntro', title: 'Page Intro', type: 'text', rows: 3}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text', rows: 4}),
        defineField({name: 'featuredEntryLabel', title: 'Featured Entry Label', type: 'string'}),
        defineField({name: 'allEntriesLabel', title: 'All Entries Label', type: 'string'}),
        defineField({name: 'detailIntroLabel', title: 'Detail Intro Label', type: 'string'}),
        defineField({name: 'detailActionsLabel', title: 'Detail Actions Label', type: 'string'}),
        defineField({name: 'detailReturnToJournalLabel', title: 'Detail Return To Journal Label', type: 'string'}),
        defineField({name: 'detailReturnToWorksLabel', title: 'Detail Return To Works Label', type: 'string'}),
        defineField({name: 'detailGalleryLabel', title: 'Detail Gallery Label', type: 'string'}),
        defineField({name: 'detailContinueReadingLabel', title: 'Detail Continue Reading Label', type: 'string'}),
        defineField({name: 'detailPreviousEntryLabel', title: 'Detail Previous Entry Label', type: 'string'}),
        defineField({name: 'detailNextEntryLabel', title: 'Detail Next Entry Label', type: 'string'}),
        defineField({name: 'detailStartOfJournalLabel', title: 'Detail Start Of Journal Label', type: 'string'}),
        defineField({name: 'detailEndOfJournalLabel', title: 'Detail End Of Journal Label', type: 'string'}),
        defineField({name: 'orbitLabel', title: 'Orbit Label', type: 'string'}),
        defineField({name: 'orbitDescription', title: 'Orbit Description', type: 'text', rows: 3}),
        defineField({name: 'spreadLabel', title: 'Spread Label', type: 'string'}),
        defineField({name: 'mixLabel', title: 'Mix Label', type: 'string'}),
        defineField({name: 'selectedEntryLabel', title: 'Selected Entry Label', type: 'string'}),
        defineField({name: 'selectedEntryFallback', title: 'Selected Entry Fallback', type: 'text', rows: 3}),
        defineField({name: 'previousLabel', title: 'Previous Label', type: 'string'}),
        defineField({name: 'nextLabel', title: 'Next Label', type: 'string'}),
        defineField({name: 'enterEntryLabel', title: 'Enter Entry Label', type: 'string'}),
      ],
    }),

    defineField({
      name: 'albumPage',
      title: 'My Album Page',
      type: 'object',
      group: 'album',
      fields: [
        defineField({name: 'pageLabel', title: 'Page Label', type: 'string'}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'description', title: 'Description', type: 'text', rows: 4}),
        defineField({name: 'emptyStateLabel', title: 'Empty State Label', type: 'string'}),
        defineField({name: 'emptyStateTitle', title: 'Empty State Title', type: 'string'}),
        defineField({name: 'emptyStateDescription', title: 'Empty State Description', type: 'text', rows: 3}),
        defineField({name: 'orbitalLabel', title: 'Orbital Label', type: 'string'}),
        defineField({name: 'orbitalDescription', title: 'Orbital Description', type: 'text', rows: 3}),
        defineField({name: 'alignFramesLabel', title: 'Align Frames Label', type: 'string'}),
        defineField({name: 'returnToOrbitLabel', title: 'Return To Orbit Label', type: 'string'}),
        defineField({name: 'selectedFrameLabel', title: 'Selected Frame Label', type: 'string'}),
        defineField({name: 'selectedFrameFallback', title: 'Selected Frame Fallback', type: 'text', rows: 3}),
        defineField({name: 'navigationLabel', title: 'Navigation Label', type: 'string'}),
        defineField({name: 'previousLabel', title: 'Previous Label', type: 'string'}),
        defineField({name: 'nextLabel', title: 'Next Label', type: 'string'}),
      ],
    }),

    defineField({
      name: 'contact',
      title: 'Contact',
      type: 'object',
      group: 'contact',
      fields: [
        defineField({name: 'sectionLabel', title: 'Section Label', type: 'string'}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'body', title: 'Body', type: 'text', rows: 4}),
        defineField({name: 'emailLabel', title: 'Email Label', type: 'string'}),
        defineField({name: 'instagramLabel', title: 'Instagram Label', type: 'string'}),
        defineField({name: 'worksLabel', title: 'Works Label', type: 'string'}),
        defineField({name: 'journalLabel', title: 'Journal Label', type: 'string'}),
        defineField({name: 'albumLabel', title: 'Album Label', type: 'string'}),
      ],
    }),
  ],
})